---
# ====== Application: Sample Cards ===========================
id: 104
identification: 
  name: Sample Cards
  alias: SAMPLE-CARDS
  version: 24.2.0
  application-group: Sample Apps # 13313791473822207

row-search: 
  tokenize: false
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: false
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: N
  copyright-banner: |
    Name: #APP_NAME#
    Copyright (c) 2012, #YEAR# Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0
    as shown at https://oss.oracle.com/licenses/upl/

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Application Express Accounts # 11344150081145837822

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Disabled
  embed-in-frames: Allow from same origin
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: APEX_DEV

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Sample Cards

progressive-web-app: 
  enable: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&SESSION.'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Desktop Navigation Menu # 11344150862123837826

navigation-bar: 
  implementation: List
  list: Desktop Navigation Bar # 11344289269676838006
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#APP_IMAGES#app-icon.css?version=#APP_VERSION#'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: true
  auto-dismiss-success-messages: false

subscription: 
  version-number: 185292856

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Sample Cards

- # ====== Substitution: JET_VISUALIZATION_URL =================
  id: 2
  identification: 
    name: JET_VISUALIZATION_URL

  value: 
    static-value: 'https://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=home&demo=rootVisualizations'

- # ====== Substitution: MOVIEDB_API ===========================
  id: 3
  identification: 
    name: MOVIEDB_API

  value: 
    static-value: 'https://www.themoviedb.org/documentation/api'

- # ====== Substitution: GOOGLE_API ============================
  id: 4
  identification: 
    name: GOOGLE_API

  value: 
    static-value: 'https://developers.google.com/youtube/v3/docs'

- # ====== Substitution: PRODUCT_NAME ==========================
  id: 5
  identification: 
    name: PRODUCT_NAME

  value: 
    static-value: Oracle APEX

component-settings: 
- # ====== Component Setting: NATIVE_BOSS ======================
  id: 10525251858255931
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 175361843

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 12116987924749076
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 37167665078883

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 12117410481749076
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 37167665078883

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 12137904736590748
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 155471871

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 617349504659038458
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 37166093908906

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 5478701774067159205
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 37166093908918

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 5500296811398023706
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 37166093908918

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 5502071109065748768
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 37166093908918

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 11344147983774837820
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 37166093908918

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 11344148300808837821
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 37166093908918

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 11344148556893837821
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 37166093908918

- # ====== Component Setting: NATIVE_IR ========================
  id: 11344149236538837821
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 37166093908918

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 11344149537660837821
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 37166093908918

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 11344149786590837822
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 37166093908918

